"""
Run this once to seed all 26 Exellar projects into the database.
Usage: python seed_projects.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
os.environ.setdefault('FLASK_ENV', 'development')

from app import create_app
from app.extensions import db
from app.models.project import Project

PROJECTS = [
    {
        'title': 'Multistar Autograph',
        'category': 'High-Rise Construction',
        'status': 'ongoing',
        'location': 'Oshiwara, Mumbai',
        'client_name': 'Multistar',
        'scope': 'High-Rise Residential',
        'size': '2 Towers G+40 · ~5,00,000 sft',
        'story_headline': '2 Towers G+40 · ~5,00,000 sft',
        'story_body': 'Complete civil works including RCC, masonry, plaster, UG & OH tanks.',
    },
    {
        'title': 'Concrete 3D Printing, IIT Mumbai',
        'category': 'Institutional / R&D',
        'status': 'ongoing',
        'location': 'Powai, Mumbai',
        'client_name': 'IIT Mumbai',
        'scope': 'Institutional Construction',
        'size': 'Prototype Structure',
        'story_headline': 'IS code compliant 3D printed structure',
        'story_body': 'First-of-its-kind IS code compliant concrete 3D printed structure in India. Structure certified by IIT Powai, Mumbai.',
    },
    {
        'title': 'Lodha Evergreen',
        'category': 'High-Rise Construction',
        'status': 'ongoing',
        'location': 'Vikhroli, Mumbai',
        'client_name': 'Lodha Group',
        'scope': 'High-Rise Residential',
        'size': '2 Towers G+35 · ~7,50,000 sft',
        'story_headline': '2 Towers G+35 · ~7,50,000 sft',
        'story_body': 'Complete civil works including RCC, masonry, plaster, UG & OH tanks. Aluminium shuttering with 10-day slab cycle.',
    },
    {
        'title': 'Raheja Solaris',
        'category': 'High-Rise Construction',
        'status': 'ongoing',
        'location': 'Juinagar, Navi Mumbai',
        'client_name': 'Raheja',
        'scope': 'High-Rise Residential',
        'size': '3 Towers G+29 · ~11,00,000 sft',
        'story_headline': '3 Towers G+29 · ~11,00,000 sft',
        'story_body': 'Complete civil works for 3 tower G+29 storey, approximately 11,00,000 sft. Aluminium shuttering.',
    },
    {
        'title': 'Rustomjee Aden',
        'category': 'High-Rise Construction',
        'status': 'ongoing',
        'location': 'Bandra East, Mumbai',
        'client_name': 'Rustomjee',
        'scope': 'High-Rise Residential',
        'size': '1 Tower B+G+21 · ~1,00,000 sft',
        'story_headline': '1 Tower B+G+21 · ~1,00,000 sft',
        'story_body': 'Complete civil works for 1 Tower B+G+21 storey, approximately 1,00,000 sft. 2 basements, aluminium formwork.',
    },
    {
        'title': 'Rustomjee Ashiana',
        'category': 'High-Rise Construction',
        'status': 'ongoing',
        'location': 'Juhu Circle, Mumbai',
        'client_name': 'Rustomjee',
        'scope': 'High-Rise Residential',
        'size': '1 Tower G+13 · ~80,000 sft',
        'story_headline': '1 Tower G+13 · ~80,000 sft',
        'story_body': 'Complete civil works for 1 Tower G+13 storey, approximately 80,000 sft. 2 basements, aluminium formwork.',
    },
    {
        'title': 'General Aviation Terminal, Mumbai Airport',
        'category': 'Infrastructure Works',
        'status': 'completed',
        'location': 'Santacruz East, Mumbai',
        'client_name': 'Piramal NextGen',
        'scope': 'Infrastructure Works',
        'size': 'General Aviation Terminal',
        'story_headline': 'General Aviation Terminal at Mumbai Airport',
        'story_body': 'Complete civil works for the General Aviation Terminal at Mumbai Airport.',
    },
    {
        'title': 'Lodha Casa Supremo',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Mira Road East, Mumbai',
        'client_name': 'Lodha Group',
        'scope': 'High-Rise Residential',
        'size': '2 Towers G+32 · ~3,28,000 sft',
        'story_headline': '2 Towers G+32 · ~3,28,000 sft',
        'story_body': 'Complete civil works including RCC, masonry, plaster, UG & OH tanks for 2 nos G+32 Towers.',
    },
    {
        'title': 'Ayan Residency',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Nallasopara West, Mumbai',
        'client_name': 'Magnum Home Makers / Dudhwala Builders',
        'scope': 'High-Rise Residential',
        'size': '11 Towers G+14 · ~4,00,000 sft',
        'story_headline': '11 Towers G+14 · ~4,00,000 sft',
        'story_body': 'Complete lock & key project including infrastructure & compound development for 11 nos G+14 Towers.',
    },
    {
        'title': 'NL Aryavarta',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Dahisar, Mumbai',
        'client_name': 'Nahalchand Laloochand Pvt. Ltd.',
        'scope': 'High-Rise Residential',
        'size': '2 Towers G+23 · ~4,60,000 sft',
        'story_headline': '2 Towers G+23 · ~4,60,000 sft',
        'story_body': 'Civil works — Masonry, Internal & External Plaster works for 2 nos G+23 storey Towers.',
    },
    {
        'title': 'Crescent Nexus',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Kalina, Santacruz East, Mumbai',
        'client_name': 'Crescent Builders & Developers',
        'scope': 'High-Rise Residential',
        'size': '6 Towers 1B+G+13 · ~2,80,000 sft',
        'story_headline': '6 Towers · ~2,80,000 sft',
        'story_body': 'Complete civil works for 6 Towers 1B, G+13, approximately 2,80,000 sft.',
    },
    {
        'title': 'Rustomjee Crown',
        'category': 'Infrastructure Works',
        'status': 'completed',
        'location': 'Prabhadevi, Mumbai',
        'client_name': 'DB Realty',
        'scope': 'Infrastructure Works',
        'size': 'Infrastructure Package',
        'story_headline': 'Infrastructure & Compound Development',
        'story_body': 'Infrastructure civil works including paving, stamp concrete, compound wall, guniting, SWD etc.',
    },
    {
        'title': 'KSI Community Center, Wanowrie',
        'category': 'Community / Institutional',
        'status': 'completed',
        'location': 'Wanowrie, Pune',
        'client_name': 'Khoja Shia Isnasari Jamat',
        'scope': 'Structural Rehabilitation',
        'size': 'Community Center',
        'story_headline': 'RCC, Repairs & Structural Strengthening',
        'story_body': 'RCC, Repairs & Structural Strengthening, Waterproofing & Other Civil works.',
    },
    {
        'title': 'Crescent SkyHeights',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Dahisar East, Mumbai',
        'client_name': 'Crescent Builders & Developers',
        'scope': 'High-Rise Residential',
        'size': 'G+16 Tower · ~53,000 sft',
        'story_headline': 'G+16 Tower · ~53,000 sft',
        'story_body': 'Civil works for G+16 storey Tower, approximately 53,000 sft.',
    },
    {
        'title': 'Crescent Heritage',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Bandra West, Mumbai',
        'client_name': 'Crescent Group Builders & Developers',
        'scope': 'High-Rise Residential',
        'size': 'G+3P+13 Tower · ~75,000 sft',
        'story_headline': 'G+3P+13 Tower · ~75,000 sft',
        'story_body': 'Civil works for G+3P+13 storey Tower, approximately 75,000 sft.',
    },
    {
        'title': 'Omkar 1973 Tower',
        'category': 'Structural Works',
        'status': 'completed',
        'location': 'Worli, Mumbai',
        'client_name': 'Omkar Realtors & Developers Pvt. Ltd.',
        'scope': 'Structural Rehabilitation',
        'size': 'Towers 1 & 2',
        'story_headline': 'Masonry, Plaster & Compound Works',
        'story_body': 'Masonry, internal & external plaster, compound walls, compound development & other miscellaneous works.',
    },
    {
        'title': 'St Francis Hotel Management Institute',
        'category': 'Institutional',
        'status': 'completed',
        'location': 'Borivali, Mumbai',
        'client_name': 'St. Francis Industrial Training Institute',
        'scope': 'Institutional Construction',
        'size': 'G+6 Building · ~68,000 sft',
        'story_headline': 'G+6 Building · ~68,000 sft',
        'story_body': 'Complete civil work for G+6 Hotel Management Institute Building, approx area 68,000 sft.',
    },
    {
        'title': 'KSI Community Center, Kurla',
        'category': 'Community / Institutional',
        'status': 'completed',
        'location': 'Kurla West, Mumbai',
        'client_name': 'KSI Jamaat, Mumbai',
        'scope': 'Structural Rehabilitation',
        'size': 'G+3 Community Hall',
        'story_headline': 'G+3 Community Hall, Civil & Infra Works',
        'story_body': 'Civil works for G+3 structure of community hall including part RCC, masonry, plaster, waterproofing, UG & OH tanks, retaining walls, compound development & infrastructure works.',
    },
    {
        'title': 'Kantharia Lake View',
        'category': 'Residential',
        'status': 'completed',
        'location': 'Vasai West, Mumbai',
        'client_name': 'Kantharia Group',
        'scope': 'High-Rise Residential',
        'size': 'Complete Grey Work',
        'story_headline': 'Complete Grey Work',
        'story_body': 'Complete grey work for residential development.',
    },
    {
        'title': 'Kalpataru Primus',
        'category': 'Infrastructure & Development',
        'status': 'completed',
        'location': 'Santacruz East, Mumbai',
        'client_name': 'Kalpataru',
        'scope': 'Infrastructure Works',
        'size': 'Infrastructure Package',
        'story_headline': 'Infrastructure & Compound Development',
        'story_body': 'Infrastructure & compound development works.',
    },
    {
        'title': 'Omkar Alta Monte',
        'category': 'Structural Works',
        'status': 'completed',
        'location': 'Malad East, Mumbai',
        'client_name': 'Omkar Realtors & Developers',
        'scope': 'Structural Rehabilitation',
        'size': 'Miscellaneous Package',
        'story_headline': 'Miscellaneous RCC, Masonry & Plaster Works',
        'story_body': 'Miscellaneous RCC, masonry & plaster works.',
    },
    {
        'title': 'Bramha Sky City',
        'category': 'High-Rise Construction',
        'status': 'completed',
        'location': 'Dhanori, Pune',
        'client_name': 'Bramha Realtors, Pune',
        'scope': 'High-Rise Residential',
        'size': '2 Towers G+12 · ~1,60,000 sft',
        'story_headline': '2 Towers G+12 · ~1,60,000 sft',
        'story_body': 'High-rise residential construction for 2 Towers G+12, approximately 1,60,000 sft.',
    },
    {
        'title': '1973 Sales Pavilion',
        'category': 'Commercial',
        'status': 'completed',
        'location': 'Worli, Mumbai',
        'client_name': 'Omkar Realtors & Developers',
        'scope': 'Commercial Works',
        'size': 'Sales Pavilion',
        'story_headline': 'Masonry, Plaster & Compound Works',
        'story_body': 'Masonry, plaster & compound works for the iconic 1973 sales pavilion.',
    },
    {
        'title': 'KSI Arambaug',
        'category': 'Community / Institutional',
        'status': 'completed',
        'location': 'Mumbai',
        'client_name': 'KSI Jamaat, Mumbai',
        'scope': 'Structural Rehabilitation',
        'size': 'Community Building',
        'story_headline': 'Structural Repairs, Waterproofing, Painting',
        'story_body': 'Structural repairs, waterproofing & painting works.',
    },
    {
        'title': 'K. S. Floritech Park',
        'category': 'Industrial',
        'status': 'completed',
        'location': 'MIDC Talegaon, Pune',
        'client_name': 'K. S. Floritech',
        'scope': 'Industrial Construction',
        'size': 'Industrial Facility',
        'story_headline': 'Industrial Facility, MIDC Talegaon',
        'story_body': 'Industrial construction works at MIDC Talegaon, Pune.',
    },
    {
        'title': 'B3 Mantralay',
        'category': 'Landscaping',
        'status': 'completed',
        'location': 'Mumbai',
        'client_name': 'Mr. Rajendra Mulak',
        'scope': 'Landscaping Works',
        'size': 'Private Residence',
        'story_headline': 'Landscaping, Patio, Deck, Hardscaping',
        'story_body': 'Landscaping, patio, deck & hardscaping works for premium private residence.',
    },
]


def run():
    app = create_app()
    with app.app_context():
        added = 0
        skipped = 0
        for p in PROJECTS:
            exists = Project.query.filter_by(title=p['title']).first()
            if exists:
                skipped += 1
                continue
            proj = Project(**p)
            db.session.add(proj)
            added += 1

        db.session.commit()
        print(f'Done. Added {added} projects, skipped {skipped} duplicates.')


if __name__ == '__main__':
    run()
